name: "PR Image Width Adjuster"
description: "Automatically converts markdown images to HTML img tags with width attribute in PR descriptions"
inputs:
  width:
    description: "Target width for images in pixels"
    required: false
    default: "300"
  token:
    description: "GitHub token for API access"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "image"
  color: "blue"
