name: Resize Images

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  resize-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Resize Images
        uses: your-username/image-resize-github-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          width: 300
