name: Adjust Image Widths

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  adjust-image-widths:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Adjust image widths in PR description
        uses: mljlynch/image-resize-github-action@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          width: 300 # Set the desired width for images in PR descriptions
